window.screenOrientation = "portrait", 
// loadLib("libs/laya.core.js"),
//  loadLib("libs/laya.webgl.js"), 
// loadLib("libs/laya.ani.js"), 
// loadLib("libs/laya.ui.js"), 
// loadLib("YYGGames/YYGGames.js"), 
// loadLib("libs/des.js"), 
// loadLib("libs/laya.effect.js"), 
// loadLib("libs/laya.d3.js"), 
loadLib("code.js");