// require("weapp-adapter.js"), require("libs/laya.wxmini.js"), window.loadLib = require,
    window.screenOrientation = "portrait", 
    loadLib("libs/laya.core.js"), 
    loadLib("libs/laya.webgl.js"),
    loadLib("libs/laya.ui.js"), 
    loadLib("libs/laya.d3.js"), 
    loadLib("libs/laya.particle.js"),
    loadLib("libs/CommonFrame/GlobalInit.js"), 
    loadLib("libs/CommonFrame/Bilog.js"),
    loadLib("libs/CommonFrame/BiStatLog.js"), 
    loadLib("libs/CommonFrame/EncodeDecode.js"),
    loadLib("libs/CommonFrame/EventType.js"),
    loadLib("libs/CommonFrame/HttpUtil.js"),
    loadLib("libs/CommonFrame/NotificationCenter.js"), 
    loadLib("libs/CommonFrame/PropagateInterface.js"),
    loadLib("libs/CommonFrame/ShareInterface.js"), 
    loadLib("libs/CommonFrame/TCPClient.js"),
    loadLib("libs/CommonFrame/Timer.js"), 
    loadLib("libs/CommonFrame/TuyooSDK.js"), 
    loadLib("libs/CommonFrame/Util.js"),
    loadLib("js/bundle.js")
    // , 
    // window.Parser = require("./src/dom/dom_parser");